/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class DomainElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Domain");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSpecificationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cObjectsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cObjectsObjectParserRuleCall_3_0 = (RuleCall)cObjectsAssignment_3.eContents().get(0);
		private final Assignment cConstraintsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cConstraintsConstraintParserRuleCall_4_0 = (RuleCall)cConstraintsAssignment_4.eContents().get(0);
		private final Assignment cScenariosAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cScenariosScenarioParserRuleCall_5_0 = (RuleCall)cScenariosAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Domain:
		//	'specification' name=ID '{'
		//	objects+=Object*
		//	constraints+=Constraint*
		//	scenarios+=Scenario* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'specification' name=ID '{' objects+=Object* constraints+=Constraint* scenarios+=Scenario* '}'
		public Group getGroup() { return cGroup; }
		
		//'specification'
		public Keyword getSpecificationKeyword_0() { return cSpecificationKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//objects+=Object*
		public Assignment getObjectsAssignment_3() { return cObjectsAssignment_3; }
		
		//Object
		public RuleCall getObjectsObjectParserRuleCall_3_0() { return cObjectsObjectParserRuleCall_3_0; }
		
		//constraints+=Constraint*
		public Assignment getConstraintsAssignment_4() { return cConstraintsAssignment_4; }
		
		//Constraint
		public RuleCall getConstraintsConstraintParserRuleCall_4_0() { return cConstraintsConstraintParserRuleCall_4_0; }
		
		//scenarios+=Scenario*
		public Assignment getScenariosAssignment_5() { return cScenariosAssignment_5; }
		
		//Scenario
		public RuleCall getScenariosScenarioParserRuleCall_5_0() { return cScenariosScenarioParserRuleCall_5_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class ScenarioElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Scenario");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cScenarioKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cScenariocontentsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cScenariocontentsScenarioContentParserRuleCall_3_0 = (RuleCall)cScenariocontentsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Scenario:
		//	'scenario' name=ID '{'
		//	scenariocontents+=ScenarioContent*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'scenario' name=ID '{' scenariocontents+=ScenarioContent* '}'
		public Group getGroup() { return cGroup; }
		
		//'scenario'
		public Keyword getScenarioKeyword_0() { return cScenarioKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//scenariocontents+=ScenarioContent*
		public Assignment getScenariocontentsAssignment_3() { return cScenariocontentsAssignment_3; }
		
		//ScenarioContent
		public RuleCall getScenariocontentsScenarioContentParserRuleCall_3_0() { return cScenariocontentsScenarioContentParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ScenarioContentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ScenarioContent");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cAltAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cAltAltParserRuleCall_0_0 = (RuleCall)cAltAssignment_0.eContents().get(0);
		private final Assignment cMessageAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cMessageMessageParserRuleCall_1_0 = (RuleCall)cMessageAssignment_1.eContents().get(0);
		private final Assignment cParAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final RuleCall cParParParserRuleCall_2_0 = (RuleCall)cParAssignment_2.eContents().get(0);
		private final Assignment cLoopAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final RuleCall cLoopLoopParserRuleCall_3_0 = (RuleCall)cLoopAssignment_3.eContents().get(0);
		
		//ScenarioContent:
		//	alt+=Alt | message+=Message | par+=Par | loop+=Loop;
		@Override public ParserRule getRule() { return rule; }
		
		//alt+=Alt | message+=Message | par+=Par | loop+=Loop
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//alt+=Alt
		public Assignment getAltAssignment_0() { return cAltAssignment_0; }
		
		//Alt
		public RuleCall getAltAltParserRuleCall_0_0() { return cAltAltParserRuleCall_0_0; }
		
		//message+=Message
		public Assignment getMessageAssignment_1() { return cMessageAssignment_1; }
		
		//Message
		public RuleCall getMessageMessageParserRuleCall_1_0() { return cMessageMessageParserRuleCall_1_0; }
		
		//par+=Par
		public Assignment getParAssignment_2() { return cParAssignment_2; }
		
		//Par
		public RuleCall getParParParserRuleCall_2_0() { return cParParParserRuleCall_2_0; }
		
		//loop+=Loop
		public Assignment getLoopAssignment_3() { return cLoopAssignment_3; }
		
		//Loop
		public RuleCall getLoopLoopParserRuleCall_3_0() { return cLoopLoopParserRuleCall_3_0; }
	}
	public class MessageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Message");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMessageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cRequiredAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final Keyword cRequiredRequiredKeyword_2_0 = (Keyword)cRequiredAssignment_2.eContents().get(0);
		private final Assignment cFailAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final Keyword cFailFailKeyword_3_0 = (Keyword)cFailAssignment_3.eContents().get(0);
		private final Assignment cStrictAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final Keyword cStrictStrictKeyword_4_0 = (Keyword)cStrictAssignment_4.eContents().get(0);
		private final Assignment cSenderAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cSenderObjectCrossReference_5_0 = (CrossReference)cSenderAssignment_5.eContents().get(0);
		private final RuleCall cSenderObjectIDTerminalRuleCall_5_0_1 = (RuleCall)cSenderObjectCrossReference_5_0.eContents().get(1);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cReceiverAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cReceiverObjectCrossReference_7_0 = (CrossReference)cReceiverAssignment_7.eContents().get(0);
		private final RuleCall cReceiverObjectIDTerminalRuleCall_7_0_1 = (RuleCall)cReceiverObjectCrossReference_7_0.eContents().get(1);
		private final Assignment cPastAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final Keyword cPastPastKeyword_8_0 = (Keyword)cPastAssignment_8.eContents().get(0);
		private final Assignment cFutureAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final Keyword cFutureFutureKeyword_9_0 = (Keyword)cFutureAssignment_9.eContents().get(0);
		private final Assignment cConstraintAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final Keyword cConstraintConstraintKeyword_10_0 = (Keyword)cConstraintAssignment_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cCAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final CrossReference cCConstraintCrossReference_12_0 = (CrossReference)cCAssignment_12.eContents().get(0);
		private final RuleCall cCConstraintIDTerminalRuleCall_12_0_1 = (RuleCall)cCConstraintCrossReference_12_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cSemicolonKeyword_14 = (Keyword)cGroup.eContents().get(14);
		
		//Message:
		//	'message' name=Name required?='required'? fail?='fail'? strict?='strict'?
		//	sender=[Object] '->' receiver=[Object] past?='past'? future?='future'? constraint?='constraint'?
		//	'{'? c=[Constraint]? '}'? ';';
		@Override public ParserRule getRule() { return rule; }
		
		//'message' name=Name required?='required'? fail?='fail'? strict?='strict'? sender=[Object] '->' receiver=[Object]
		//past?='past'? future?='future'? constraint?='constraint'? '{'? c=[Constraint]? '}'? ';'
		public Group getGroup() { return cGroup; }
		
		//'message'
		public Keyword getMessageKeyword_0() { return cMessageKeyword_0; }
		
		//name=Name
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//Name
		public RuleCall getNameNameParserRuleCall_1_0() { return cNameNameParserRuleCall_1_0; }
		
		//required?='required'?
		public Assignment getRequiredAssignment_2() { return cRequiredAssignment_2; }
		
		//'required'
		public Keyword getRequiredRequiredKeyword_2_0() { return cRequiredRequiredKeyword_2_0; }
		
		//fail?='fail'?
		public Assignment getFailAssignment_3() { return cFailAssignment_3; }
		
		//'fail'
		public Keyword getFailFailKeyword_3_0() { return cFailFailKeyword_3_0; }
		
		//strict?='strict'?
		public Assignment getStrictAssignment_4() { return cStrictAssignment_4; }
		
		//'strict'
		public Keyword getStrictStrictKeyword_4_0() { return cStrictStrictKeyword_4_0; }
		
		//sender=[Object]
		public Assignment getSenderAssignment_5() { return cSenderAssignment_5; }
		
		//[Object]
		public CrossReference getSenderObjectCrossReference_5_0() { return cSenderObjectCrossReference_5_0; }
		
		//ID
		public RuleCall getSenderObjectIDTerminalRuleCall_5_0_1() { return cSenderObjectIDTerminalRuleCall_5_0_1; }
		
		//'->'
		public Keyword getHyphenMinusGreaterThanSignKeyword_6() { return cHyphenMinusGreaterThanSignKeyword_6; }
		
		//receiver=[Object]
		public Assignment getReceiverAssignment_7() { return cReceiverAssignment_7; }
		
		//[Object]
		public CrossReference getReceiverObjectCrossReference_7_0() { return cReceiverObjectCrossReference_7_0; }
		
		//ID
		public RuleCall getReceiverObjectIDTerminalRuleCall_7_0_1() { return cReceiverObjectIDTerminalRuleCall_7_0_1; }
		
		//past?='past'?
		public Assignment getPastAssignment_8() { return cPastAssignment_8; }
		
		//'past'
		public Keyword getPastPastKeyword_8_0() { return cPastPastKeyword_8_0; }
		
		//future?='future'?
		public Assignment getFutureAssignment_9() { return cFutureAssignment_9; }
		
		//'future'
		public Keyword getFutureFutureKeyword_9_0() { return cFutureFutureKeyword_9_0; }
		
		//constraint?='constraint'?
		public Assignment getConstraintAssignment_10() { return cConstraintAssignment_10; }
		
		//'constraint'
		public Keyword getConstraintConstraintKeyword_10_0() { return cConstraintConstraintKeyword_10_0; }
		
		//'{'?
		public Keyword getLeftCurlyBracketKeyword_11() { return cLeftCurlyBracketKeyword_11; }
		
		//c=[Constraint]?
		public Assignment getCAssignment_12() { return cCAssignment_12; }
		
		//[Constraint]
		public CrossReference getCConstraintCrossReference_12_0() { return cCConstraintCrossReference_12_0; }
		
		//ID
		public RuleCall getCConstraintIDTerminalRuleCall_12_0_1() { return cCConstraintIDTerminalRuleCall_12_0_1; }
		
		//'}'?
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
		
		//';'
		public Keyword getSemicolonKeyword_14() { return cSemicolonKeyword_14; }
	}
	public class NameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Name");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Alternatives cAlternatives_2 = (Alternatives)cGroup.eContents().get(2);
		private final RuleCall cIDTerminalRuleCall_2_0 = (RuleCall)cAlternatives_2.eContents().get(0);
		private final RuleCall cNumberTerminalRuleCall_2_1 = (RuleCall)cAlternatives_2.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Name:
		//	ID '(' (ID | Number)? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//ID '(' (ID | Number)? ')'
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//(ID | Number)?
		public Alternatives getAlternatives_2() { return cAlternatives_2; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_2_0() { return cIDTerminalRuleCall_2_0; }
		
		//Number
		public RuleCall getNumberTerminalRuleCall_2_1() { return cNumberTerminalRuleCall_2_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
	}
	public class ObjectTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ObjectType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cObjectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//ObjectType:
		//	'object' name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//'object' name=ID
		public Group getGroup() { return cGroup; }
		
		//'object'
		public Keyword getObjectKeyword_0() { return cObjectKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class ObjectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Object");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cObjectAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cObjectObjectTypeParserRuleCall_0_0 = (RuleCall)cObjectAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Object:
		//	object+=ObjectType name=ID ';';
		@Override public ParserRule getRule() { return rule; }
		
		//object+=ObjectType name=ID ';'
		public Group getGroup() { return cGroup; }
		
		//object+=ObjectType
		public Assignment getObjectAssignment_0() { return cObjectAssignment_0; }
		
		//ObjectType
		public RuleCall getObjectObjectTypeParserRuleCall_0_0() { return cObjectObjectTypeParserRuleCall_0_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2() { return cSemicolonKeyword_2; }
	}
	public class ConstraintElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Constraint");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConstraintKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMessagesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMessagesMessageParserRuleCall_3_0 = (RuleCall)cMessagesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Constraint:
		//	'constraint' name=ID '{'
		//	messages+=Message*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'constraint' name=ID '{' messages+=Message* '}'
		public Group getGroup() { return cGroup; }
		
		//'constraint'
		public Keyword getConstraintKeyword_0() { return cConstraintKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//messages+=Message*
		public Assignment getMessagesAssignment_3() { return cMessagesAssignment_3; }
		
		//Message
		public RuleCall getMessagesMessageParserRuleCall_3_0() { return cMessagesMessageParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class AltElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Alt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAltKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cExpressionsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cExpressionsExpressionParserRuleCall_1_0 = (RuleCall)cExpressionsAssignment_1.eContents().get(0);
		
		//Alt:
		//	'alt' expressions+=Expression*;
		@Override public ParserRule getRule() { return rule; }
		
		//'alt' expressions+=Expression*
		public Group getGroup() { return cGroup; }
		
		//'alt'
		public Keyword getAltKeyword_0() { return cAltKeyword_0; }
		
		//expressions+=Expression*
		public Assignment getExpressionsAssignment_1() { return cExpressionsAssignment_1; }
		
		//Expression
		public RuleCall getExpressionsExpressionParserRuleCall_1_0() { return cExpressionsExpressionParserRuleCall_1_0; }
	}
	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Expression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cGreaterThanSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLessThanSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cGreaterThanSignEqualsSignKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLessThanSignEqualsSignKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Alternatives cAlternatives_7 = (Alternatives)cGroup.eContents().get(7);
		private final RuleCall cIDTerminalRuleCall_7_0 = (RuleCall)cAlternatives_7.eContents().get(0);
		private final RuleCall cNumberTerminalRuleCall_7_1 = (RuleCall)cAlternatives_7.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cLeftCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cMessagesAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cMessagesMessageParserRuleCall_10_0 = (RuleCall)cMessagesAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Expression:
		//	'(' ID? '='? '>'? '<'? '>='? '<='? (ID | Number)? ')' '{'
		//	messages+=Message*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' ID? '='? '>'? '<'? '>='? '<='? (ID | Number)? ')' '{' messages+=Message* '}'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//ID?
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
		
		//'='?
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//'>'?
		public Keyword getGreaterThanSignKeyword_3() { return cGreaterThanSignKeyword_3; }
		
		//'<'?
		public Keyword getLessThanSignKeyword_4() { return cLessThanSignKeyword_4; }
		
		//'>='?
		public Keyword getGreaterThanSignEqualsSignKeyword_5() { return cGreaterThanSignEqualsSignKeyword_5; }
		
		//'<='?
		public Keyword getLessThanSignEqualsSignKeyword_6() { return cLessThanSignEqualsSignKeyword_6; }
		
		//(ID | Number)?
		public Alternatives getAlternatives_7() { return cAlternatives_7; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_7_0() { return cIDTerminalRuleCall_7_0; }
		
		//Number
		public RuleCall getNumberTerminalRuleCall_7_1() { return cNumberTerminalRuleCall_7_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8() { return cRightParenthesisKeyword_8; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9() { return cLeftCurlyBracketKeyword_9; }
		
		//messages+=Message*
		public Assignment getMessagesAssignment_10() { return cMessagesAssignment_10; }
		
		//Message
		public RuleCall getMessagesMessageParserRuleCall_10_0() { return cMessagesMessageParserRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ParElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Par");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cParexpressionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParexpressionParExpressionParserRuleCall_2_0 = (RuleCall)cParexpressionAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Par:
		//	'par' '{' parexpression+=ParExpression* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'par' '{' parexpression+=ParExpression* '}'
		public Group getGroup() { return cGroup; }
		
		//'par'
		public Keyword getParKeyword_0() { return cParKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//parexpression+=ParExpression*
		public Assignment getParexpressionAssignment_2() { return cParexpressionAssignment_2; }
		
		//ParExpression
		public RuleCall getParexpressionParExpressionParserRuleCall_2_0() { return cParexpressionParExpressionParserRuleCall_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class ParExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ParExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCaseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMessagesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMessagesMessageParserRuleCall_3_0 = (RuleCall)cMessagesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ParExpression:
		//	'case' name=ID '{' messages+=Message* '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'case' name=ID '{' messages+=Message* '}'
		public Group getGroup() { return cGroup; }
		
		//'case'
		public Keyword getCaseKeyword_0() { return cCaseKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//messages+=Message*
		public Assignment getMessagesAssignment_3() { return cMessagesAssignment_3; }
		
		//Message
		public RuleCall getMessagesMessageParserRuleCall_3_0() { return cMessagesMessageParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class LoopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Loop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMinAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMinNumberTerminalRuleCall_2_0 = (RuleCall)cMinAssignment_2.eContents().get(0);
		private final Keyword cCommaKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMaxAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMaxNumberTerminalRuleCall_4_0 = (RuleCall)cMaxAssignment_4.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cMessagesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cMessagesMessageParserRuleCall_7_0 = (RuleCall)cMessagesAssignment_7.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Loop:
		//	'loop' '(' min+=Number ',' max+=Number ')' '{'
		//	messages+=Message*
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'loop' '(' min+=Number ',' max+=Number ')' '{' messages+=Message* '}'
		public Group getGroup() { return cGroup; }
		
		//'loop'
		public Keyword getLoopKeyword_0() { return cLoopKeyword_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1() { return cLeftParenthesisKeyword_1; }
		
		//min+=Number
		public Assignment getMinAssignment_2() { return cMinAssignment_2; }
		
		//Number
		public RuleCall getMinNumberTerminalRuleCall_2_0() { return cMinNumberTerminalRuleCall_2_0; }
		
		//','
		public Keyword getCommaKeyword_3() { return cCommaKeyword_3; }
		
		//max+=Number
		public Assignment getMaxAssignment_4() { return cMaxAssignment_4; }
		
		//Number
		public RuleCall getMaxNumberTerminalRuleCall_4_0() { return cMaxNumberTerminalRuleCall_4_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5() { return cRightParenthesisKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//messages+=Message*
		public Assignment getMessagesAssignment_7() { return cMessagesAssignment_7; }
		
		//Message
		public RuleCall getMessagesMessageParserRuleCall_7_0() { return cMessagesMessageParserRuleCall_7_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	
	
	private final DomainElements pDomain;
	private final ScenarioElements pScenario;
	private final ScenarioContentElements pScenarioContent;
	private final MessageElements pMessage;
	private final NameElements pName;
	private final TerminalRule tNumber;
	private final ObjectTypeElements pObjectType;
	private final ObjectElements pObject;
	private final ConstraintElements pConstraint;
	private final AltElements pAlt;
	private final ExpressionElements pExpression;
	private final ParElements pPar;
	private final ParExpressionElements pParExpression;
	private final LoopElements pLoop;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pDomain = new DomainElements();
		this.pScenario = new ScenarioElements();
		this.pScenarioContent = new ScenarioContentElements();
		this.pMessage = new MessageElements();
		this.pName = new NameElements();
		this.tNumber = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Number");
		this.pObjectType = new ObjectTypeElements();
		this.pObject = new ObjectElements();
		this.pConstraint = new ConstraintElements();
		this.pAlt = new AltElements();
		this.pExpression = new ExpressionElements();
		this.pPar = new ParElements();
		this.pParExpression = new ParExpressionElements();
		this.pLoop = new LoopElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Domain:
	//	'specification' name=ID '{'
	//	objects+=Object*
	//	constraints+=Constraint*
	//	scenarios+=Scenario* '}';
	public DomainElements getDomainAccess() {
		return pDomain;
	}
	
	public ParserRule getDomainRule() {
		return getDomainAccess().getRule();
	}
	
	//Scenario:
	//	'scenario' name=ID '{'
	//	scenariocontents+=ScenarioContent*
	//	'}';
	public ScenarioElements getScenarioAccess() {
		return pScenario;
	}
	
	public ParserRule getScenarioRule() {
		return getScenarioAccess().getRule();
	}
	
	//ScenarioContent:
	//	alt+=Alt | message+=Message | par+=Par | loop+=Loop;
	public ScenarioContentElements getScenarioContentAccess() {
		return pScenarioContent;
	}
	
	public ParserRule getScenarioContentRule() {
		return getScenarioContentAccess().getRule();
	}
	
	//Message:
	//	'message' name=Name required?='required'? fail?='fail'? strict?='strict'?
	//	sender=[Object] '->' receiver=[Object] past?='past'? future?='future'? constraint?='constraint'?
	//	'{'? c=[Constraint]? '}'? ';';
	public MessageElements getMessageAccess() {
		return pMessage;
	}
	
	public ParserRule getMessageRule() {
		return getMessageAccess().getRule();
	}
	
	//Name:
	//	ID '(' (ID | Number)? ')';
	public NameElements getNameAccess() {
		return pName;
	}
	
	public ParserRule getNameRule() {
		return getNameAccess().getRule();
	}
	
	//terminal Number:
	//	'0'..'9'*;
	public TerminalRule getNumberRule() {
		return tNumber;
	}
	
	//ObjectType:
	//	'object' name=ID;
	public ObjectTypeElements getObjectTypeAccess() {
		return pObjectType;
	}
	
	public ParserRule getObjectTypeRule() {
		return getObjectTypeAccess().getRule();
	}
	
	//Object:
	//	object+=ObjectType name=ID ';';
	public ObjectElements getObjectAccess() {
		return pObject;
	}
	
	public ParserRule getObjectRule() {
		return getObjectAccess().getRule();
	}
	
	//Constraint:
	//	'constraint' name=ID '{'
	//	messages+=Message*
	//	'}';
	public ConstraintElements getConstraintAccess() {
		return pConstraint;
	}
	
	public ParserRule getConstraintRule() {
		return getConstraintAccess().getRule();
	}
	
	//Alt:
	//	'alt' expressions+=Expression*;
	public AltElements getAltAccess() {
		return pAlt;
	}
	
	public ParserRule getAltRule() {
		return getAltAccess().getRule();
	}
	
	//Expression:
	//	'(' ID? '='? '>'? '<'? '>='? '<='? (ID | Number)? ')' '{'
	//	messages+=Message*
	//	'}';
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}
	
	//Par:
	//	'par' '{' parexpression+=ParExpression* '}';
	public ParElements getParAccess() {
		return pPar;
	}
	
	public ParserRule getParRule() {
		return getParAccess().getRule();
	}
	
	//ParExpression:
	//	'case' name=ID '{' messages+=Message* '}';
	public ParExpressionElements getParExpressionAccess() {
		return pParExpression;
	}
	
	public ParserRule getParExpressionRule() {
		return getParExpressionAccess().getRule();
	}
	
	//Loop:
	//	'loop' '(' min+=Number ',' max+=Number ')' '{'
	//	messages+=Message*
	//	'}';
	public LoopElements getLoopAccess() {
		return pLoop;
	}
	
	public ParserRule getLoopRule() {
		return getLoopAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
