/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.ContextMessageContent;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Context Message Content</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ContextMessageContentImpl#isRequired <em>Required</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ContextMessageContentImpl#isFail <em>Fail</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ContextMessageContentImpl#isStrict <em>Strict</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ContextMessageContentImpl#getName <em>Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContextMessageContentImpl extends ContextMessageImpl implements ContextMessageContent
{
  /**
   * The default value of the '{@link #isRequired() <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRequired()
   * @generated
   * @ordered
   */
  protected static final boolean REQUIRED_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isRequired() <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isRequired()
   * @generated
   * @ordered
   */
  protected boolean required = REQUIRED_EDEFAULT;

  /**
   * The default value of the '{@link #isFail() <em>Fail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFail()
   * @generated
   * @ordered
   */
  protected static final boolean FAIL_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isFail() <em>Fail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isFail()
   * @generated
   * @ordered
   */
  protected boolean fail = FAIL_EDEFAULT;

  /**
   * The default value of the '{@link #isStrict() <em>Strict</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isStrict()
   * @generated
   * @ordered
   */
  protected static final boolean STRICT_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isStrict() <em>Strict</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isStrict()
   * @generated
   * @ordered
   */
  protected boolean strict = STRICT_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContextMessageContentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.CONTEXT_MESSAGE_CONTENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isRequired()
  {
    return required;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setRequired(boolean newRequired)
  {
    boolean oldRequired = required;
    required = newRequired;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONTEXT_MESSAGE_CONTENT__REQUIRED, oldRequired, required));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isFail()
  {
    return fail;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFail(boolean newFail)
  {
    boolean oldFail = fail;
    fail = newFail;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONTEXT_MESSAGE_CONTENT__FAIL, oldFail, fail));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isStrict()
  {
    return strict;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setStrict(boolean newStrict)
  {
    boolean oldStrict = strict;
    strict = newStrict;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONTEXT_MESSAGE_CONTENT__STRICT, oldStrict, strict));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CONTEXT_MESSAGE_CONTENT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__REQUIRED:
        return isRequired();
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__FAIL:
        return isFail();
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__STRICT:
        return isStrict();
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__NAME:
        return getName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__REQUIRED:
        setRequired((Boolean)newValue);
        return;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__FAIL:
        setFail((Boolean)newValue);
        return;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__STRICT:
        setStrict((Boolean)newValue);
        return;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__NAME:
        setName((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__REQUIRED:
        setRequired(REQUIRED_EDEFAULT);
        return;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__FAIL:
        setFail(FAIL_EDEFAULT);
        return;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__STRICT:
        setStrict(STRICT_EDEFAULT);
        return;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__NAME:
        setName(NAME_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__REQUIRED:
        return required != REQUIRED_EDEFAULT;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__FAIL:
        return fail != FAIL_EDEFAULT;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__STRICT:
        return strict != STRICT_EDEFAULT;
      case MyDslPackage.CONTEXT_MESSAGE_CONTENT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (required: ");
    result.append(required);
    result.append(", fail: ");
    result.append(fail);
    result.append(", strict: ");
    result.append(strict);
    result.append(", name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ContextMessageContentImpl
