/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clock Constraint Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ClockConstraintExpression#isNot <em>Not</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ClockConstraintExpression#getLclockconstraint <em>Lclockconstraint</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ClockConstraintExpression#getRclockconstraint <em>Rclockconstraint</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getClockConstraintExpression()
 * @model
 * @generated
 */
public interface ClockConstraintExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Not</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Not</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Not</em>' attribute.
   * @see #setNot(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getClockConstraintExpression_Not()
   * @model
   * @generated
   */
  boolean isNot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ClockConstraintExpression#isNot <em>Not</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Not</em>' attribute.
   * @see #isNot()
   * @generated
   */
  void setNot(boolean value);

  /**
   * Returns the value of the '<em><b>Lclockconstraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lclockconstraint</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lclockconstraint</em>' containment reference.
   * @see #setLclockconstraint(ClockConstraint)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getClockConstraintExpression_Lclockconstraint()
   * @model containment="true"
   * @generated
   */
  ClockConstraint getLclockconstraint();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ClockConstraintExpression#getLclockconstraint <em>Lclockconstraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lclockconstraint</em>' containment reference.
   * @see #getLclockconstraint()
   * @generated
   */
  void setLclockconstraint(ClockConstraint value);

  /**
   * Returns the value of the '<em><b>Rclockconstraint</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rclockconstraint</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rclockconstraint</em>' containment reference.
   * @see #setRclockconstraint(ClockConstraint)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getClockConstraintExpression_Rclockconstraint()
   * @model containment="true"
   * @generated
   */
  ClockConstraint getRclockconstraint();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ClockConstraintExpression#getRclockconstraint <em>Rclockconstraint</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rclockconstraint</em>' containment reference.
   * @see #getRclockconstraint()
   * @generated
   */
  void setRclockconstraint(ClockConstraint value);

} // ClockConstraintExpression
