/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Message</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ContextMessage#getContent <em>Content</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ContextMessage#isRequired <em>Required</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ContextMessage#isFail <em>Fail</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ContextMessage#isStrict <em>Strict</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContextMessage()
 * @model
 * @generated
 */
public interface ContextMessage extends EObject
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ContextMessageContent}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Content</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContextMessage_Content()
   * @model containment="true"
   * @generated
   */
  EList<ContextMessageContent> getContent();

  /**
   * Returns the value of the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Required</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required</em>' attribute.
   * @see #setRequired(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContextMessage_Required()
   * @model
   * @generated
   */
  boolean isRequired();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ContextMessage#isRequired <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Required</em>' attribute.
   * @see #isRequired()
   * @generated
   */
  void setRequired(boolean value);

  /**
   * Returns the value of the '<em><b>Fail</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fail</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fail</em>' attribute.
   * @see #setFail(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContextMessage_Fail()
   * @model
   * @generated
   */
  boolean isFail();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ContextMessage#isFail <em>Fail</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fail</em>' attribute.
   * @see #isFail()
   * @generated
   */
  void setFail(boolean value);

  /**
   * Returns the value of the '<em><b>Strict</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Strict</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strict</em>' attribute.
   * @see #setStrict(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getContextMessage_Strict()
   * @model
   * @generated
   */
  boolean isStrict();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.ContextMessage#isStrict <em>Strict</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strict</em>' attribute.
   * @see #isStrict()
   * @generated
   */
  void setStrict(boolean value);

} // ContextMessage
