/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fragment Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isInt <em>Int</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isFloat <em>Float</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isString <em>String</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isBoolean <em>Boolean</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isGreater <em>Greater</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isSmaller <em>Smaller</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isGreaterequals <em>Greaterequals</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isSmallerequals <em>Smallerequals</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isEquals <em>Equals</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isNotequals <em>Notequals</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute()
 * @model
 * @generated
 */
public interface FragmentAttribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Int</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int</em>' attribute.
   * @see #setInt(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Int()
   * @model
   * @generated
   */
  boolean isInt();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isInt <em>Int</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int</em>' attribute.
   * @see #isInt()
   * @generated
   */
  void setInt(boolean value);

  /**
   * Returns the value of the '<em><b>Float</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Float</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Float</em>' attribute.
   * @see #setFloat(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Float()
   * @model
   * @generated
   */
  boolean isFloat();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isFloat <em>Float</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Float</em>' attribute.
   * @see #isFloat()
   * @generated
   */
  void setFloat(boolean value);

  /**
   * Returns the value of the '<em><b>String</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>String</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>String</em>' attribute.
   * @see #setString(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_String()
   * @model
   * @generated
   */
  boolean isString();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isString <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>String</em>' attribute.
   * @see #isString()
   * @generated
   */
  void setString(boolean value);

  /**
   * Returns the value of the '<em><b>Boolean</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Boolean</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean</em>' attribute.
   * @see #setBoolean(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Boolean()
   * @model
   * @generated
   */
  boolean isBoolean();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isBoolean <em>Boolean</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boolean</em>' attribute.
   * @see #isBoolean()
   * @generated
   */
  void setBoolean(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Greater</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Greater</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greater</em>' attribute.
   * @see #setGreater(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Greater()
   * @model
   * @generated
   */
  boolean isGreater();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isGreater <em>Greater</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Greater</em>' attribute.
   * @see #isGreater()
   * @generated
   */
  void setGreater(boolean value);

  /**
   * Returns the value of the '<em><b>Smaller</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Smaller</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smaller</em>' attribute.
   * @see #setSmaller(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Smaller()
   * @model
   * @generated
   */
  boolean isSmaller();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isSmaller <em>Smaller</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Smaller</em>' attribute.
   * @see #isSmaller()
   * @generated
   */
  void setSmaller(boolean value);

  /**
   * Returns the value of the '<em><b>Greaterequals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Greaterequals</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greaterequals</em>' attribute.
   * @see #setGreaterequals(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Greaterequals()
   * @model
   * @generated
   */
  boolean isGreaterequals();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isGreaterequals <em>Greaterequals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Greaterequals</em>' attribute.
   * @see #isGreaterequals()
   * @generated
   */
  void setGreaterequals(boolean value);

  /**
   * Returns the value of the '<em><b>Smallerequals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Smallerequals</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Smallerequals</em>' attribute.
   * @see #setSmallerequals(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Smallerequals()
   * @model
   * @generated
   */
  boolean isSmallerequals();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isSmallerequals <em>Smallerequals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Smallerequals</em>' attribute.
   * @see #isSmallerequals()
   * @generated
   */
  void setSmallerequals(boolean value);

  /**
   * Returns the value of the '<em><b>Equals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Equals</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Equals</em>' attribute.
   * @see #setEquals(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Equals()
   * @model
   * @generated
   */
  boolean isEquals();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isEquals <em>Equals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Equals</em>' attribute.
   * @see #isEquals()
   * @generated
   */
  void setEquals(boolean value);

  /**
   * Returns the value of the '<em><b>Notequals</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Notequals</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notequals</em>' attribute.
   * @see #setNotequals(boolean)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Notequals()
   * @model
   * @generated
   */
  boolean isNotequals();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#isNotequals <em>Notequals</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Notequals</em>' attribute.
   * @see #isNotequals()
   * @generated
   */
  void setNotequals(boolean value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFragmentAttribute_Value()
   * @model
   * @generated
   */
  String getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.FragmentAttribute#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(String value);

} // FragmentAttribute
