/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario Content</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ScenarioContent#getAlt <em>Alt</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ScenarioContent#getMessage <em>Message</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ScenarioContent#getPar <em>Par</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ScenarioContent#getLoop <em>Loop</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ScenarioContent#getContextmessage <em>Contextmessage</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ScenarioContent#getParamConstraint <em>Param Constraint</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ScenarioContent#getAssertentity <em>Assertentity</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ScenarioContent#getAssertrelation <em>Assertrelation</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent()
 * @model
 * @generated
 */
public interface ScenarioContent extends EObject
{
  /**
   * Returns the value of the '<em><b>Alt</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Alt}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Alt</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alt</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent_Alt()
   * @model containment="true"
   * @generated
   */
  EList<Alt> getAlt();

  /**
   * Returns the value of the '<em><b>Message</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Message}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Message</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent_Message()
   * @model containment="true"
   * @generated
   */
  EList<Message> getMessage();

  /**
   * Returns the value of the '<em><b>Par</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Par}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Par</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent_Par()
   * @model containment="true"
   * @generated
   */
  EList<Par> getPar();

  /**
   * Returns the value of the '<em><b>Loop</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Loop}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Loop</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent_Loop()
   * @model containment="true"
   * @generated
   */
  EList<Loop> getLoop();

  /**
   * Returns the value of the '<em><b>Contextmessage</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ContextMessage}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contextmessage</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contextmessage</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent_Contextmessage()
   * @model containment="true"
   * @generated
   */
  EList<ContextMessage> getContextmessage();

  /**
   * Returns the value of the '<em><b>Param Constraint</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.ParameterConstraint}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Param Constraint</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Param Constraint</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent_ParamConstraint()
   * @model containment="true"
   * @generated
   */
  EList<ParameterConstraint> getParamConstraint();

  /**
   * Returns the value of the '<em><b>Assertentity</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.AssertionEntity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assertentity</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assertentity</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent_Assertentity()
   * @model containment="true"
   * @generated
   */
  EList<AssertionEntity> getAssertentity();

  /**
   * Returns the value of the '<em><b>Assertrelation</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.AssertionRelation}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assertrelation</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assertrelation</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenarioContent_Assertrelation()
   * @model containment="true"
   * @generated
   */
  EList<AssertionRelation> getAssertrelation();

} // ScenarioContent
