/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unary Logical Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getUnaryLogicalExpression()
 * @model
 * @generated
 */
public interface UnaryLogicalExpression extends LogicalExpression
{
} // UnaryLogicalExpression
