package org.xtext.example.mydsl.generator;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

@SuppressWarnings("all")
public class IClockGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public interface IClock {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public long getClock(String clock);");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void resetClock(String clock);");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile("IClock.java", _builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("import java.util.HashMap;");
    _builder_1.newLine();
    _builder_1.append("import java.util.Map;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("import org.apache.commons.lang3.time.StopWatch;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("public class Clock implements IClock {");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("private Map<String, StopWatch> stopwatches;");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("public Clock() {");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("stopwatches = new HashMap<>();");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("@Override");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("public long getClock(String clock) {");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("if (stopwatches.containsKey(clock)) {");
    _builder_1.newLine();
    _builder_1.append("\t\t\t");
    _builder_1.append("return stopwatches.get(clock).getTime();");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("return -1;");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("@Override");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("public void resetClock(String clock) {");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("if (stopwatches.containsKey(clock)) {");
    _builder_1.newLine();
    _builder_1.append("\t\t\t");
    _builder_1.append("stopwatches.get(clock).reset();");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("} else {");
    _builder_1.newLine();
    _builder_1.append("\t\t\t");
    _builder_1.append("StopWatch watch = new StopWatch();");
    _builder_1.newLine();
    _builder_1.append("\t\t\t");
    _builder_1.append("watch.start();");
    _builder_1.newLine();
    _builder_1.append("\t\t\t");
    _builder_1.append("stopwatches.put(clock, watch);");
    _builder_1.newLine();
    _builder_1.append("\t\t");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.append("\t");
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    fsa.generateFile("Clock.java", _builder_1);
  }
}
