package org.xtext.example.mydsl.generator;

import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

@SuppressWarnings("all")
public class StateGenerator extends AbstractGenerator {
  @Override
  public void doGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public class State {");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private String id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("private StateType type;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public State() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.id = \"q0\";");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.type = StateType.NORMAL;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public State(String id, StateType stateType) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.id = id;");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.type = stateType;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public String getId() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public StateType getType() {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("return type;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setType(StateType type) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.type = type;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void setId(String id) {");
    _builder.newLine();
    _builder.append("        ");
    _builder.append("this.id = id;");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("    ");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("public void writeState(){");
    _builder.newLine();
    _builder.append("    \t");
    _builder.append("System.out.println(this.id + \" \" + this.type);");
    _builder.newLine();
    _builder.append("    ");
    _builder.append("}");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    fsa.generateFile("State.java", _builder);
    StringConcatenation _builder_1 = new StringConcatenation();
    _builder_1.append("public enum StateType {");
    _builder_1.newLine();
    _builder_1.append("    ");
    _builder_1.append("NORMAL, ACCEPT, FINAL, ACCEPT_ALL");
    _builder_1.newLine();
    _builder_1.append("}");
    _builder_1.newLine();
    _builder_1.newLine();
    fsa.generateFile("StateType.java", _builder_1);
  }
}
