/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl.scoping;

import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
import org.xtext.example.mydsl.myDsl.AppearMessage;
import org.xtext.example.mydsl.myDsl.AssertionEntity;
import org.xtext.example.mydsl.myDsl.AssertionRelation;
import org.xtext.example.mydsl.myDsl.ChangeToMessage;
import org.xtext.example.mydsl.myDsl.ChangeToRelation;
import org.xtext.example.mydsl.myDsl.DisappearMessage;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MyDslScopeProvider extends AbstractDeclarativeScopeProvider {
  public IScope scope_ChangeToMessage_attribute(final ChangeToMessage ctx, final EReference ref) {
    return Scopes.scopeFor(ctx.getEntity().getAttributes());
  }
  
  public IScope scope_ChangeToMessage_entity(final ChangeToMessage ctx, final EReference ref) {
    return Scopes.scopeFor(ctx.getContext().getEntities());
  }
  
  public IScope scope_ChangeToRelation_relation(final ChangeToRelation ctx, final EReference ref) {
    return Scopes.scopeFor(ctx.getContext().getRelations());
  }
  
  public IScope scope_ChangeToRelation_attribute(final ChangeToRelation ctx, final EReference ref) {
    return Scopes.scopeFor(ctx.getRelation().getAttributes());
  }
  
  public IScope scope_AppearMessage_entity(final AppearMessage app, final EReference ref) {
    return Scopes.scopeFor(app.getContext().getEntities());
  }
  
  public IScope scope_DisappearMessage_entity(final DisappearMessage dis, final EReference ref) {
    return Scopes.scopeFor(dis.getContext().getEntities());
  }
  
  public IScope scope_AssertionEntity_entity(final AssertionEntity assert_, final EReference ref) {
    return Scopes.scopeFor(assert_.getContext().getEntities());
  }
  
  public IScope scope_AssertionEntity_attribute(final AssertionEntity assert_, final EReference ref) {
    return Scopes.scopeFor(assert_.getEntity().getAttributes());
  }
  
  public IScope scope_AssertionRelation_relation(final AssertionRelation assert_, final EReference ref) {
    return Scopes.scopeFor(assert_.getContext().getRelations());
  }
  
  public IScope scope_AssertionRelation_attribute(final AssertionRelation assert_, final EReference ref) {
    return Scopes.scopeFor(assert_.getRelation().getAttributes());
  }
}
